### ISSUE TITLE
ImportError: No Module named ardrone_autonomy.msg

### ISSUE THREAD

**Issue by rabenimmermehr** [mikehamer/ardrone_tutorials#2]
Hey Mike,

I already left you a comment on your blog, but it appeared to me that it might be more useful and get more attention here ;)

While trying to execute your first tutorial, I get the following error while starting the keyboard-controller:

```
process[keyboard_controller-3]: started with pid [1683]
Traceback (most recent call last):
File "/home/ardrone/ros_workspace/ardrone_tutorials/src/keyboard_controller.py", line 13, in <module>
from drone_controller import BasicDroneController
File "/home/ardrone/ros_workspace/ardrone_tutorials/src/drone_controller.py", line 17, in <module>
from ardrone_autonomy.msg import Navdata # for receiving navdata feedback
ImportError: No module named ardrone_autonomy.msg
================================================================================REQUIRED process [keyboard_controller-3] has died!
process has died [pid 1683, exit code 1, cmd /home/ardrone/ros_workspace/ardrone_tutorials/src/keyboard_controller.py __name:=keyboard_controller __log:=/home/ardrone/.ros/log/f04ce202-2ff6-11e3-8948-080027393fbf/keyboard_controller-3.log].
log file: /home/ardrone/.ros/log/f04ce202-2ff6-11e3-8948-080027393fbf/keyboard_controller-3*.log
Initiating shutdown!
```

What is the missing "ardrone_autonomy.msg"? Is it a header or a topic from ROS? Sorry if that's a stupid question, I am new to ROS.

Thanks in advance,
Fabian

**Comment by rabenimmermehr** [comment]
As additional information,

```
rosmsg show ardrone_autonomy/Navdata
```

shows the desired information.

**Comment by rabenimmermehr** [comment]
Mike fixed it with the latest patch

**Comment by cipri-tom** [comment]
Hey,
Do you know what the fix was ? I am getting this error while using a custom build of ardrone_autonomy. 
Thanks!
